blog/urls.py
from django.urls import path
from .views import (
    home_page,
    post_detail,
    post_create,
    PostUpdate,
    PostDeleteView,
    login_page,
    logout_page,
    user_post_list,
    UsersPostListView,
    comment_page,
    about_page,
)

app_name = 'blog'
urlpatterns = [
    path('', home_page, name='home_page'),
    path('about/', about_page, name='about_page'),
    path('userpost/', user_post_list, name='user_post_list'),
    path('userpost/<str:username>',
         UsersPostListView.as_view(), name='users_post_list'),
    path('new-post/', post_create, name='post_create'),
    path('comment/<int:pk>-<str:slug>/', comment_page, name='comment_page'),
    path('login/', login_page, name='login_page'),
    path('logout/', logout_page, name='logout_page'),
    path('post/<int:pk>-<str:slug>/', post_detail, name='post_detail'),
    path('post/<int:pk>-<str:slug>/update/',
         PostUpdate.as_view(), name='post_update'),
    path('post/<int:pk>-<str:slug>/delete/',
         PostDeleteView.as_view(), name='post_delete'),

]

myproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_view
from django.urls import path, include
from userprofile.views import search_query
from userprofile.forms import MyPasswordResetForm, MySetPasswordForm

urlpatterns = [
    path('', include('blog.urls')),
    path('register', include('userprofile.urls')),
    path('search/', search_query, name='search_query'),
    path('reset-password/', auth_view.PasswordResetView.as_view(template_name='userprofile/password_reset.html', form_class=MyPasswordResetForm),
         name='reset_password'),
    path('reset-password/done/', auth_view.PasswordResetDoneView.as_view(template_name='userprofile/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name='userprofile/password_reset_confirm.html', form_class=MySetPasswordForm),
         name='password_reset_confirm'),
    path('reset-password-complete/', auth_view.PasswordResetCompleteView.as_view(template_name='userprofile/password_reset_complete.html'),
         name='password_reset_complete'),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.urls import path
from .views import user_registration, user_profile


app_name = 'userprofile'
urlpatterns = [
    path('', user_registration, name='user_registration'),
    path('profile/', user_profile, name='user_profile'),
]

blog/models.py
from django.db import models
from django.utils import timezone
# from django.db.models.signals import pre_saves
# from .utils import unique_slug_generator
from django.utils.text import slugify
from django.urls import reverse
from django.conf import settings
from django.db.models import Q

User = settings.AUTH_USER_MODEL


class PostQuerySet(models.QuerySet):
    def search(self, query):
        return self.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(user__username__icontains=query)
        )


class PostManager(models.Manager):
    def get_queryset(self):
        return PostQuerySet(self.model, using=self._db)

    def search(self, query=None):
        if query is None:
            return self.get_queryset().none()
        return self.get_queryset().search(query)


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='blog_img', blank=True, null=True)
    title = models.CharField(max_length=250)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    slug = models.SlugField(max_length=250, default='', editable=False)
    objects = PostManager()

    class Meta:
        ordering = ['-date_posted']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        kwargs = {
            "pk": self.id,
            "slug": self.slug,

        }
        return reverse("blog:post_detail", kwargs=kwargs)

    def get_edit_url(self):
        kwargs = {
            "pk": self.id,
            "slug": self.slug,

        }
        return reverse("blog:post_update", kwargs=kwargs)

    def get_delete_url(self):
        kwargs = {
            "pk": self.id,
            "slug": self.slug,

        }
        return reverse("blog:post_delete", kwargs=kwargs)

    def get_comment_url(self):
        kwargs = {
            "pk": self.id,
            "slug": self.slug,

        }
        return reverse("blog:comment_page", kwargs=kwargs)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(
        Post, related_name='comments', on_delete=models.CASCADE)
    content = models.TextField()
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

blog/forms.py
from django import forms
from .models import Post, Comment
from django.contrib.auth.forms import AuthenticationForm


class UserAuthenticationForm(AuthenticationForm):
    username = forms.CharField(max_length=150, widget=forms.TextInput(
        attrs={'class': 'input-control'}))
    password = forms.CharField(label='password',
                               max_length=32, widget=forms.PasswordInput(attrs={'class': 'input-control'}))

    class Meta:
        fields = ['username', 'password']


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'input-control'}),
            'content': forms.Textarea(attrs={'class': 'input-control'}),
            'image': forms.FileInput(attrs={'class': 'file-control'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

        widgets = {
            'content': forms.Textarea(attrs={'class': 'input-control'}),
        }

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post
from .forms import PostForm, CommentForm, UserAuthenticationForm
from django.contrib import messages
from django.views.generic import UpdateView, DeleteView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.db.models import Q
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


def home_page(request):
    post = Post.objects.all()
    paginator = Paginator(post, 5)
    page = request.GET.get('page')
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)
    index = items.number - 1
    max_index = len(paginator.page_range)
    start_index = index - 5 if index >= 5 else 0
    end_index = index + 5 if index <= 5 else max_index
    page_range = paginator.page_range[start_index:end_index]

    context = {
        'posts': items,
        'page_range': page_range
    }
    return render(request, 'blog/home_page.html', context)


def about_page(request):
    context = {}
    return render(request, 'blog/about.html', context)


def post_detail(request, slug, pk):
    post = get_object_or_404(Post, slug=slug, pk=pk)
    context = {
        'post': post
    }

    return render(request, 'blog/post_detail.html', context)


class UsersPostListView(ListView):
    model = Post
    template_name = 'blog/user_post.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(user=user).order_by('-date_posted')


def user_post_list(request):
    if request.user.is_authenticated:
        user = request.user
        user_post = Post.objects.filter(user=user)
    else:
        user_post = Post.objects.all()
    paginator = Paginator(user_post, 5)
    page = request.GET.get('page')
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)
    index = items.number - 1
    max_index = len(paginator.page_range)
    start_index = index - 5 if index >= 5 else 0
    end_index = index + 5 if index <= 5 else max_index
    page_range = paginator.page_range[start_index:end_index]
    context = {
        'posts': items,
        'page_range': page_range
    }
    return render(request, 'blog/user_post_list.html', context)


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.save()
            messages.success(request, f'Post created successfully.')
            return redirect('blog:home_page')
        else:
            for msg in form.error_messages:
                messages.warning(request, f'Error: {form.error_messages}')
    else:
        form = PostForm()
    context = {
        'form': form
    }

    return render(request, 'blog/post_form.html', context)


class PostUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = 'blog/post_update_form.html'
    form_class = PostForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.user:
            return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.user:
            return True
        return False


def login_page(request):
    if request.method == 'POST':
        form = UserAuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(
                    request, f'You have logged in successfully as {username}')
                return redirect('blog:home_page')
            else:
                messages.warning(
                    request, 'Username or password is incorrect, please provide the valid data')
        else:
            messages.warning(
                request, 'Username or password is incorrect, please provide the valid data')

    form = UserAuthenticationForm()

    context = {
        'form': form
    }
    return render(request, 'blog/login.html', context)


def logout_page(request):
    if request.user:
        logout(request)
        messages.info(
            request, 'You have been logged out successfully. Please login again')
        return redirect('blog:login_page')


@login_required
def comment_page(request, slug, pk):
    post = get_object_or_404(Post, slug=slug, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            obj.post = post
            obj.save()
            messages.success(request, 'Your comment is saved successfully')
            return redirect('blog:post_detail', slug=post.slug, pk=post.id)
    else:
        form = CommentForm()
        context = {
            'form': form
        }
    return render(request, 'blog/comment_page.html', context)

blog/templates/blog/about.html
{% extends 'blog/base.html' %}
{% block content %}
<article class="profile">
      <div class="profile-info">
        <div class="post-heading py-3">
        <h3 class="new-post-heading">About Us</h3>
        <div class="underline mx-auto"></div>
      </div>
        <p>I am Ojo Philip Odeniyi, a student of University of Ibadan where I'm currently studying Medicine and Surgery. I am also a web developer and I love God.</p>
        <p>My vision is to become a full stack web developer in the very nearest future(I'm working on this currently by God's grace!) and also not to neglect my course of study. So help me God</p>
        <p>Do you wish to have your own website?</p>
        <p>Do you wish to become a web developer and need a coach?</p>
        <p>We can make your dreams become true, just <strong>contact us</strong>  by clicking on any of the icons below. </p>
      </div>
      <div class="footer-icons">
        <a href="https://mobile.facebook.com/?hrc=1&refsrc=http%3A%2F%2Fh.facebook.com%2Fhr%2Fr&_rdc=1&_rdr"><i class="fab fa-facebook footer-icon" target='_blank'></i></a>
        <a href="https://mobile.twitter.com/OdeniyiOjo" target='_blank'><i class="fab fa-twitter footer-icon"></i></a>
        <a href="https://mail.google.com/mail/u/?authuser=ojophilipodeniyi@gmail.com" target='_blank'><i class="fab fa-google footer-icon"></i></a>
      </div>
    </article>
{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Med Blog</title>
  <!--style css-->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!--fontawesome-->
  <script src="{% static 'js/all.js' %}"></script>
</head>
<body>
{% include 'blog/navbar.html' %}
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <strong>{{ message }}</strong> 
      </div>
      <script>
        $(".alert").alert();
      </script>
    {% endfor %}
  {% endif %}
{% block content %}

{% endblock content %}


{% include 'blog/footer.html' %}
  <script src="{% static 'js/script.js' %}"></script>
  <script src="{% static 'js/googlejquery.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

blog/templates/blog/comment_page.html
{% extends 'blog/base.html' %}
{% block content %}
  <!-- New Post -->
    <article class="new-post">
      <div class="post-heading">
        <h2 class="new-post-heading">Your comment</h2>
        <div class="underline"></div>
      </div>
      <form  method="POST">{% csrf_token %}
        {{ form.as_p }}
      <button type="submit" class="btn-blue">Post</button>      
      </form>
    </article>
    <!-- end of new post -->
{% endblock content %}

blog/templates/blog/delete.html
{% extends 'blog/base.html' %}
{% block content %}
  <!-- New Post -->
    <article class="new-post">
      <div class="post-heading">
        <h2 class="new-post-heading">Do you want to delete this post?</h2>
        <h2 class="new-post-heading">"{{ object.title }}"</h2>

        <div class="underline"></div>
      </div>
      <form action="." method="POST">
      {% csrf_token %}
        {{ form.as_p }}
      <button type="submit" class="btn-green">Register</button>
      <p class="new-post-heading">You already have an account? <a href="{% url 'blog:login_page' %}" class="btn-blue">Sign In</a></p> 
      </form>
    </article>
    <!-- end of new post -->
{% endblock content %}

blog/templates/blog/footer.html
<footer class="footer">
      <div class="footer-icons">
        <a href="https://mobile.facebook.com/?hrc=1&refsrc=http%3A%2F%2Fh.facebook.com%2Fhr%2Fr&_rdc=1&_rdr" target='_blank'><i class="fab fa-facebook footer-icon"></i></a>
        <a href="https://mobile.twitter.com/OdeniyiOjo"><i class="fab fa-twitter footer-icon" target='_blank'></i></a>
        <a href="https://mail.google.com/mail/u/?authuser=ojophilipodeniyi@gmail.com" target='_blank'><i class="fab fa-google footer-icon"></i></a>
      </div>
      <h4 class="footer-text">
        &copy;<span class="year"> 2020</span>
        MedBlog. all right reserved.
      </h4>
      <ul class="footer-links">
        <li class="footer-link-item"><a href="{% url 'blog:home_page' %}">Blog</a></li>
        <li class="footer-link-item"><a href="{% url 'userprofile:user_profile' %}">profile</a></li>
        <li class="footer-link-item"><a href="{% url 'userprofile:user_registration' %}">sign up</a></li>
        <li class="footer-link-item"><a href="{% url 'blog:login_page' %}">login</a></li>
      </ul>
      <p>~designed by ojophilip</p>
    </footer>

blog/templates/blog/home_page.html
{% extends 'blog/base.html' %}
{% block content %}

<!-- post card -->
    <div class="section-center">
    {% for post in posts %}
    
      <!-- single post -->
      <article class="flex-item">
        <div class="post-card">
        {% if post.image %}
          <div class="post-img-container">
            <a href="{{ post.get_absolute_url }}"><img src="{{ post.image.url }}" alt="" /></a>
          </div>
           {% endif %}
          <div class="post-content">
            <a href="{{ post.get_absolute_url }} "><h4 class="post-title">{{post.title}}</h4></a>
            <p class="post-text">
              {{ post.content|linebreaks|truncatewords:30}}
            </p>
            <p class="post-date">posted by <a href="{% url 'blog:users_post_list' post.user.username %}"><strong>
        <img class="article-img" src="{{ post.user.userprofile.image.url }}" />{{ post.user }}</strong></a> on {{ post.date_posted|date:'F d, Y' }}</p>
        <p  class="post-date font-italic"><a href="{{ post.get_absolute_url }}"> <strong>{{ post.comments.count }}</strong> comment<span class='text-lowercase'>(s)</span></a></p>
          </div>
          <div class="comment-icon">
            <a href="{{ post.get_comment_url }}"><i class="far fa-comment"></i></a>
          </div>
       
          
        </div>
      </article>
    {% endfor %}

      </div>
{% include 'blog/pagination.html' %}

      <!-- end single post -->
      {% endblock content %}

blog/templates/blog/login.html
{% extends 'blog/base.html' %}
{% block content %}
  <!-- New Post -->
    <article class="new-post">
      <div class="post-heading">
        <h3 class="new-post-heading">login here</h3>
        <div class="underline"></div>
      </div>
      <form  method="POST">{% csrf_token %}
        {{ form.as_p }}
      <button type="submit" class="btn-green">Sign In</button><span class="new-post-heading ml-4">Forgot Password? <a href="{% url 'reset_password' %}" >Reset password</a> </span>
      <p class="new-post-heading">You Don't have an account? <a href="{% url 'userprofile:user_registration' %}" class="btn-blue">Sign Up</a></p>      
      </form>
    </article>
    <!-- end of new post -->
{% endblock content %}

blog/templates/blog/navbar.html
<nav class="navbarnav" id="navbar">
      <div class="navbar-top">
        <div class="brand-name"><a href="{% url 'blog:home_page' %}"><i class="fas fa-user-md"></i></a></div>
        <div class="nav-btn"><i class="fas fa-bars"></i></div>
      </div>
      <div class="links-container">
        <div class="navbar-item">
          <ul class="links">
            <div class="left">
              <li class="link-item"><a href="{% url 'blog:home_page' %}" class="">Home</a></li>
              <li class="link-item"><a href="{% url 'blog:about_page' %}" class="">About</a></li>
              <li class="link-item"><a href="{% url 'blog:user_post_list' %}" class="">{{ request.user }}</a></li>
            </div>
            <div class="right">
            {% if user.is_authenticated %}
              <li class="link-item"><a href="{% url 'userprofile:user_profile' %}" class="">Profile</a></li>
              <li class="link-item"><a href="{% url 'blog:post_create' %}" class="">New Post</a></li>
              <li class="link-item"><a href="{% url 'blog:logout_page' %}" class="">Logout</a></li>
              {% else %}
              <li class="link-item"><a href="{% url 'blog:login_page' %}" class="">Login</a></li>
              <li class="link-item"><a href="{% url 'userprofile:user_registration' %}" class="">Register</a></li>
              {% endif %}
            </div>
          </ul>
          <div class="nav-form">
            <form action="{% url 'search_query' %}" class="form" method="GET">
              <input type="search" class="control" placeholder="Search" name='q' values='{{ request.GET.q }}'/>
              <button class="search-btn">search</button>
            </form>
          </div>
        </div>
      </div>
    </nav>
    <!-- scroll-top -->
    <div class="scroll-top">
      <span
        ><a href="#"><i class="fas fa-arrow-up"></i></a
      ></span>
    </div>
    <!-- endscroll-top -->

blog/templates/blog/pagination.html
<!-- pagination -->
   {% if posts.has_other_pages %}
    <div class="pagination-container">
      <ul class="pagination">
                  {% if posts.has_previous %}
        <li class="pagination-item">
          <a href="?page={{ posts.previous_page_number }}" class="btn-blue">prev</a>
        </li>
        {% endif %}
        {% for i in page_range %}
        {% if posts.number == i %}
        <li class="pagination-item">
          <a href="?page={{ i }}" class="btn-blue active">{{ i }}</a>
        </li>
        {% else %}
        <li class="pagination-item"><a href="?page={{ i }}" class="btn-blue">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if posts.has_next %}
        <li class="pagination-item"><a href="?page={{ posts.next_page_number }}" class="btn-blue">next</a></li>
        {% endif %}
      </ul>
    </div>
    {% endif %}
    <!-- end pagination -->

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% block content %}
  <!-- New Post -->
    <article class="new-post">
      <div class="post-heading">
        <h3 class="new-post-heading">Do you want to delete this post?</h3>
        <h3 class="new-post-heading">"{{ object.title }}"</h3>
        <div class="underline"></div>
      </div>
      <form  method="POST">{% csrf_token %}
      <button type="submit" class="btn-red">Yes, Delete</button>
      <span class="new-post-heading"><a href="{{ object.get_absolute_url }}" class="btn-blue">cancel</a></span>      
      </form>
    </article>
    <!-- end of new post -->
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}

<!-- post card -->
    <div class="row">
    <div class="col-md-8 w-90 mx-auto">
    
      <!-- single post -->
      <article class="flex-item">
        <div class="post-card">
        {% if post.image %}
          <div class="post-img-container">
            <img src="{{ post.image.url }}" alt="" />
          </div>
          {% endif %}
          <div class="post-content">
            <a href="{{ post.get_absolute_url }} "><h4 class="post-title">{{post.title}}</h4></a>
            <p class="post-text">
              {{ post.content|linebreaks }}
            </p>
            <p class="post-date">posted by <a href="{% url 'blog:users_post_list' post.user.username %}"><strong><img class="article-img" src="{{ post.user.userprofile.image.url }}" />{{ post.user.username }}</strong></a> on {{ post.date_posted|date:'F d, Y' }}</p>
            <p  class="post-date font-italic"><a href="{{ post.get_absolute_url }}"> <strong>{{ post.comments.count }}</strong> comment<span class='text-lowercase'>(s)</span></a></p>
          </div>
          {% if request.user == post.user %}
          <div class="comment-icon">
          <div class="d-flex justify-content-between align-items-center">
            <a href="{{ post.get_edit_url }}" class="btn-blue" >update</a>
            <a href="{{ post.get_delete_url }}" class="btn-red">delete</a>
            <a href="{{ post.get_comment_url }}"><i class="far fa-comment"></i></a>
          </div>
          {% else %}
           <div class="comment-icon">
            <a href="{{ post.get_comment_url }}"><i class="far fa-comment"></i></a>
          </div>
          {% endif %}
          </div>
        </div>
      </article>
      </div>
      </div>
      <div class="row">
    <div class="col-md-8 w-90 mx-auto">
    
      <!-- single comment -->
            <h2 class="post-title">Comment<span class='text-lowercase'>(s)</span></h2>

      {% for comment in post.comments.all %}
      <article class="flex-item">
        <div class="post-card">
          <div class="post-content">
            <p class="post-text">{{comment.content}}</p>
            <p class="post-date">posted by <a href="{% url 'blog:users_post_list' post.user.username %}"><strong><img class="article-img" src="{{ comment.user.userprofile.image.url }}" />{{ comment.user.username }}</strong></a> on {{ comment.date_posted|date:'F d, Y' }}</p>
          </div>
           {% comment %} <div class="comment-icon">
          <div class="d-flex justify-content-between align-items-center">
            <a href="{{ post.get_edit_url }}" class="btn-blue" >update</a>
            <a href="{{ post.get_delete_url }}" class="btn-red">delete</a>
          </div>
          </div> {% endcomment %}
        </div>
      </article>
      {% empty %}
      <article class="flex-item">
        <div class="post-card">
          <div class="post-content">
            <p class="post-title">There is no comment</p>
          </div>
        </div>
      </article>
      {% endfor %}
      </div>
      </div>
      <!-- end single comment -->
      {% endblock content %}

blog/templates/blog/post_update_form.html
{% extends 'blog/base.html' %}
{% block content %}
  <!-- New Post -->
    <article class="new-post">
      <div class="post-heading">
        <h3 class="new-post-heading">Update your post</h3>
        <div class="underline"></div>
      </div>
      <form action="." method="POST" enctype='multipart/form-data'>
      {% csrf_token %}
        {{ form.as_p }}
      <button type="submit" class="btn-blue">update</button>
      </form>
    </article>
    <!-- end of new post -->
{% endblock content %}

blog/templates/blog/user_post.html
{% extends 'blog/base.html' %}
{% block content %}

<!-- post card -->
    <div class="section-center">
    {% for post in posts %}
    
      <!-- single post -->
      <article class="flex-item">
        <div class="post-card">
        {% if post.image %}
          <div class="post-img-container">
            <a href="{{ post.get_absolute_url }}"><img src="{{ post.image.url }}" alt="" /></a>
          </div>
           {% endif %}
          <div class="post-content">
            <a href="{{ post.get_absolute_url }} "><h4 class="post-title">{{post.title}}</h4></a>
            <p class="post-text">
              {{ post.content|truncatewords:30 }}
            </p>
            <p class="post-date">posted by  <a href="{% url 'blog:users_post_list' post.user.username %}"><strong> <img class="article-img" src="{{ post.user.userprofile.image.url }}" />{{ post.user.username }}</strong></a> on {{ post.date_posted|date:'F d, Y' }}</p>
            <p  class="post-date font-italic"><a href="{{ post.get_absolute_url }}"> <strong>{{ post.comments.count }}</strong> comment<span class='text-lowercase'>(s)</span></a></p>
          </div>
          <div class="comment-icon">
            <a href="{{ post.get_comment_url }}"><i class="far fa-comment"></i></a>
          </div>
       
          
        </div>
      </article>
    {% endfor %}

      </div>
<!-- pagination -->
    {% if is_paginated %}
    <div class="pagination-container">
      <ul class="pagination">
           {% if page_obj.has_previous %}

        <li class="pagination-item">
          <a href="?page={{ page_obj.previous_page_number }}" class="btn-blue">prev</a>
        </li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
       {% if page_obj.number == i %}
        <li class="pagination-item">
          <a href="?page={{ i }}" class="btn-blue active">{{ i }}</a>
        </li>
        {% else %}
        <li class="pagination-item"><a href="?page={{ i }}" class="btn-blue">{{ i }}</a></li>
        {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="pagination-item"><a href="?page={{ page_obj.next_page_number }}" class="btn-blue">next</a></li>
        {% endif %}
      </ul>
    </div>
    {% endif %}
    <!-- end pagination -->
      <!-- end single post -->
      {% endblock content %}

blog/templates/blog/user_post_list.html
{% extends 'blog/base.html' %}
{% block content %}

<!-- post card -->
    <div class="section-center">
    {% for post in posts %}
    
      <!-- single post -->
      <article class="flex-item">
        <div class="post-card">
        {% if post.image %}
          <div class="post-img-container">
            <a href="{{ post.get_absolute_url }}"><img src="{{ post.image.url }}" alt="" /></a>
          </div>
           {% endif %}
          <div class="post-content">
            <a href="{{ post.get_absolute_url }} "><h4 class="post-title">{{post.title}}</h4></a>
            <p class="post-text">
              {{ post.content|linebreaks|truncatewords:30 }}
            </p>
            <p class="post-date">posted by  <a href="{% url 'blog:users_post_list' post.user.username %}"><strong> <img class="article-img" src="{{ post.user.userprofile.image.url }}" />{{ post.user.username }}</strong></a> on {{ post.date_posted|date:'F d, Y' }}</p>
            <p  class="post-date font-italic"><a href="{{ post.get_absolute_url }}"> <strong>{{ post.comments.count }}</strong> comment<span class='text-lowercase'>(s)</span></a></p>
          </div>
          <div class="comment-icon">
            <a href="{{ post.get_comment_url }}"><i class="far fa-comment"></i></a>
          </div>
       
          
        </div>
      </article>
    {% endfor %}

      </div>
<!-- pagination -->
{% include 'blog/pagination.html' %}
    <!-- end pagination -->
      <!-- end single post -->
      {% endblock content %}